pipeline {
    agent any

    environment {
        ARM_SUBSCRIPTION_ID = credentials('ARM_SUBSCRIPTION_ID')
        ARM_CLIENT_ID       = credentials('ARM_CLIENT_ID')
        ARM_CLIENT_SECRET   = credentials('ARM_CLIENT_SECRET')
        ARM_TENANT_ID       = credentials('ARM_TENANT_ID')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Omarmusthaq3020/jenkins.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Infra') {
                    sh "terraform init"
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Infra') {
                    sh "terraform plan"
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Infra') {
                    sh "terraform apply -auto-approve"
                }
            }
        }
    }
}
